<?php

namespace Tests\Feature;

use App\Contracts\EditorialAiClient;
use App\Models\AiEditorialRun;
use App\Models\Application;
use App\Models\ConsentRecord;
use App\Models\EditorialContent;
use App\Models\EditorialRevisionRequest;
use App\Models\Profile;
use App\Models\StaffActionLog;
use App\Models\User;
use App\Services\Ai\FakeEditorialAiClient;
use App\Services\ApplicationWorkflowService;
use App\Services\CustomerEditorialWorkflowService;
use App\Services\EditorialContentVersioningService;
use App\Services\EditorialGenerationService;
use App\Services\RazorpayPaymentService;
use App\Services\RazorpayWebhookVerifier;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Config;
use Tests\TestCase;

/**
 * GOLDEN PATH — one continuous chain from customer submission to a publicly
 * rendered bilingual profile, using the application's real routes and
 * workflow services (only the AI client is faked).
 *
 * Chain under test:
 *   customer account → application → signed webhook payment → interview
 *   → AI generation (fake) → editorial review/edit → customer preview
 *   → revision request (round 1) → revised release → customer approval
 *   → post-approval editorial change (approval invalidated, successor version)
 *   → customer re-approval → admin publication → public bilingual profile
 *   → canonical + metadata + JSON-LD + sitemap — with source material provably private.
 */
class ProfileWorkflowGoldenPathTest extends TestCase
{
    use RefreshDatabase;

    private const PRIVATE_MARKER = 'PRIVATE_SOURCE_MUST_NEVER_APPEAR_PUBLICLY_12345';

    public const EN_TITLE = 'Test Public Leader';
    public const EN_SUMMARY = 'A test biography created for the Jannayaks golden-path workflow.';
    public const EN_BODY = 'This is synthetic editorial content generated by the test AI client. It is used only to verify the editorial workflow.';
    public const ML_TITLE = 'ടെസ്റ്റ് ജനനായകൻ';
    public const ML_SUMMARY = 'സുവർണ്ണപാത പരിശോധനയ്ക്കുള്ള മലയാളം സംഗ്രഹം.';
    public const ML_BODY = 'ഇത് പരിശോധനയ്ക്കുള്ള മലയാളം എഡിറ്റോറിയൽ ഉള്ളടക്കമാണ്.';

    private FakeEditorialAiClient $ai;

    protected function setUp(): void
    {
        parent::setUp();

        Config::set('jannayaks.ai.provider', 'fake');
        Config::set('jannayaks.ai.malayalam_pipeline_enabled', true);
        Config::set('services.razorpay.enabled', false);
        Config::set('services.razorpay.webhook_secret', 'golden-path-webhook-secret');

        // Deterministic synthetic copy (test-only subclass; the shared fake's
        // behaviour is untouched for every other suite).
        $this->ai = new class extends FakeEditorialAiClient
        {
            public function generateEditorial(array $request): array
            {
                $this->requests[] = $request;

                if ((string) ($request['purpose'] ?? '') === 'malayalam') {
                    return [
                        'title' => ProfileWorkflowGoldenPathTest::ML_TITLE,
                        'summary' => ProfileWorkflowGoldenPathTest::ML_SUMMARY,
                        'body' => ProfileWorkflowGoldenPathTest::ML_BODY,
                        'claims' => [],
                        'flags' => $this->malayalamFlags,
                    ];
                }

                return [
                    'title' => ProfileWorkflowGoldenPathTest::EN_TITLE,
                    'summary' => ProfileWorkflowGoldenPathTest::EN_SUMMARY,
                    'body' => ProfileWorkflowGoldenPathTest::EN_BODY,
                    'claims' => [],
                    'flags' => $this->englishFlags,
                ];
            }
        };

        $this->app->instance(EditorialAiClient::class, $this->ai);
    }

    public function test_complete_workflow_from_customer_submission_to_public_bilingual_profile(): void
    {
        /* --------------------------------------------------------------
         * Stage 1 — customer account and application (real intake route).
         * -------------------------------------------------------------- */
        $customer = User::factory()->create(['email_verified_at' => now()]);

        $created = $this->actingAs($customer)
            ->postJson(route('applications.store'), [
                'package_tier' => 'emerging',
                'source_method' => 'online_interview',
                'full_name' => 'Golden Path Leader',
                'preferred_slug' => 'golden.path.leader',
                'contact_email' => 'golden.path@example.com',
            ])
            ->assertCreated()
            ->assertJson(['ok' => true]);

        $application = Application::query()->where('user_id', $customer->id)->sole();

        $this->assertSame($customer->id, $application->user_id);
        $this->assertSame('emerging', $application->package_tier);
        $this->assertSame(Application::PAYMENT_STATUS_PENDING, $application->payment_status);
        $this->assertSame(Application::STATUS_PAYMENT_PENDING, $application->status);
        $this->assertNull($application->profile_id, 'no profile exists before the editorial pipeline creates one');
        $this->doesntHavePublishedProfile();

        /* --------------------------------------------------------------
         * Stage 2 — payment via the existing signed webhook mechanism.
         * -------------------------------------------------------------- */
        $payment = app(RazorpayPaymentService::class)->createApplicationPaymentLink($application);
        $payment->update(['razorpay_link_id' => 'link_golden_path_1']);

        $payload = [
            'event' => 'payment.captured',
            'event_id' => 'evt_golden_path_1',
            'created_at' => time(),
            'payload' => [
                'payment' => [
                    'entity' => [
                        'id' => 'pay_golden_path_1',
                        'order_id' => null,
                        'amount' => 354000, // Recognised ₹3,000 + 18% GST, server-authoritative
                        'currency' => 'INR',
                        'notes' => [
                            'payment_id' => (string) $payment->id,
                            'application_id' => (string) $application->id,
                        ],
                    ],
                ],
                'payment_link' => ['entity' => ['id' => 'link_golden_path_1']],
            ],
        ];
        $raw = json_encode($payload, JSON_UNESCAPED_SLASHES);
        $signature = (new RazorpayWebhookVerifier)->computeSignature($raw, 'golden-path-webhook-secret');

        $this->postJson(route('payments.razorpay.webhook'), $payload, [
            RazorpayWebhookVerifier::SIGNATURE_HEADER => $signature,
            'Content-Type' => 'application/json',
        ])->assertOk()->assertJson(['ok' => true, 'paid' => true]);

        $application->refresh();
        $payment->refresh();
        $this->assertTrue($payment->isPaidOrBetter());
        $this->assertNotSame(Application::STATUS_PAYMENT_PENDING, $application->status);
        $this->assertTrue(app(\App\Services\ApplicationPaymentStateService::class)->unlocksInterviewOrUploads($application->fresh()));

        // The Online Interview is now available to the paying customer.
        $this->actingAs($customer)
            ->get(route('online-interview.show', ['application' => $application->id]))
            ->assertOk();

        /* --------------------------------------------------------------
         * Stage 3 — Online Interview submission (real routes).
         * -------------------------------------------------------------- */
        $answers = [
            'q1' => 'Golden Path Leader has served the local community since 2010, focusing on neighbourhood roads and public facilities.',
            'q2' => self::PRIVATE_MARKER.' — internal background notes about family circumstances.',
            'q5' => 'Coordinated the ward-level cleanliness campaign and the vocational training meetup.',
        ];

        $this->actingAs($customer)
            ->patchJson(route('online-interview.save', ['application' => $application->id]), ['answers' => $answers])
            ->assertOk();

        $this->actingAs($customer)
            ->postJson(route('online-interview.submit', ['application' => $application->id]))
            ->assertOk()
            ->assertJson(['ok' => true, 'next_step' => 'editorial_processing']);

        $application->refresh();
        $this->assertNotNull($application->online_interview_completed_at);
        $this->assertSame(Application::STATUS_AWAITING_EDITORIAL_REVIEW, $application->status);

        // Answers stored against the correct application and user — and private.
        $this->assertDatabaseHas('interview_answers', [
            'application_id' => $application->id,
            'user_id' => $customer->id,
            'question_id' => 'q1',
        ]);

        /* --------------------------------------------------------------
         * Stage 4 — AI generation through the real service (fake client).
         * -------------------------------------------------------------- */
        $editor = User::factory()->editor()->create();

        $run = app(EditorialGenerationService::class)
            ->generateForApplication($application->fresh(), $editor);

        $run->refresh();
        $this->assertSame(AiEditorialRun::STATUS_SUCCEEDED, $run->status);

        $profile = Profile::query()->where('user_id', $customer->id)->sole();
        $application->refresh();
        $this->assertSame($profile->id, $application->profile_id);
        $this->assertNotSame('published', $profile->status, 'AI generation must not publish');

        $english = EditorialContent::query()
            ->where('profile_id', $profile->id)
            ->where('language', EditorialContent::LANGUAGE_EN)
            ->orderByDesc('version_number')
            ->firstOrFail();
        $malayalam = EditorialContent::query()
            ->where('profile_id', $profile->id)
            ->where('language', EditorialContent::LANGUAGE_ML)
            ->orderByDesc('version_number')
            ->firstOrFail();

        $this->assertSame(EditorialContent::STATUS_DRAFT, $english->status);
        $this->assertSame(EditorialContent::STATUS_DRAFT, $malayalam->status);
        $this->assertSame(self::EN_TITLE, $english->title);
        $this->assertSame(self::EN_SUMMARY, $english->summary);
        $this->assertSame(self::ML_TITLE, $malayalam->title);
        // The Malayalam adaptation references its English master.
        $this->assertSame($english->id, $malayalam->source_editorial_content_id);

        /* --------------------------------------------------------------
         * Stage 5 — human editorial review: a real (non pass-through) edit,
         * then the editor approves the EN master (and ML) for preview.
         * -------------------------------------------------------------- */
        app(EditorialContentVersioningService::class)->applyEditorUpdate(
            $english,
            ['body' => self::EN_BODY."\n\nReviewed by the editorial desk; chronology confirmed against source material."],
            $editor,
        );
        $english->refresh();
        $this->assertStringContainsString('Reviewed by the editorial desk', $english->body);

        // Editor approval of the reviewed drafts is required before preview.
        $english->forceFill([
            'status' => EditorialContent::STATUS_APPROVED,
            'reviewed_by_id' => $editor->id,
        ])->save();
        $malayalam->forceFill([
            'status' => EditorialContent::STATUS_APPROVED,
            'reviewed_by_id' => $editor->id,
        ])->save();

        $workflow = app(CustomerEditorialWorkflowService::class);
        $application = $workflow->releaseForCustomerPreview($application->fresh(), $editor);

        $this->assertSame(Application::STATUS_EDITORIAL_APPROVED, $application->status);
        $this->assertNotNull($application->customer_preview_released_at);
        $this->assertSame('customer_preview', $profile->fresh()->status, 'preview must not publish the profile');

        // Customer preview is visible to its owner, hidden from others.
        $this->actingAs($customer)
            ->get(route('applications.preview', $application))
            ->assertOk();
        $this->actingAs(User::factory()->create())
            ->get(route('applications.preview', $application))
            ->assertForbidden();

        /* --------------------------------------------------------------
         * Stage 7a — correction loop BEFORE approval (round 1).
         * -------------------------------------------------------------- */
        $revision = $workflow->requestRevision(
            $application->fresh(),
            $customer,
            'Please mention the vocational training programme in the opening summary.',
            EditorialRevisionRequest::TYPE_REVISION,
        );

        $this->assertSame(1, $revision->round_number);
        $this->assertSame($application->id, $revision->application_id);
        $this->assertSame(EditorialRevisionRequest::STATUS_SUBMITTED, $revision->status);
        $this->assertSame(Application::STATUS_EDITORIAL_REVISION_REQUESTED, $application->fresh()->status);

        // Editor revises the approved master — the immutability rule creates
        // a successor version (draft) — then re-releases, which auto-completes
        // the open revision request.
        $revisedEnglish = app(EditorialContentVersioningService::class)->applyEditorUpdate(
            $english->fresh(),
            ['summary' => self::EN_SUMMARY.' The summary also notes the vocational training programme.'],
            $editor,
        );

        $this->assertNotSame($english->id, $revisedEnglish->id, 'approved master is immutable — revision creates a successor version');
        $this->assertSame($english->version_number + 1, $revisedEnglish->version_number);

        // The revised draft is reviewed and approved by the editor before the
        // re-release, exactly as in Stage 5. Staff also re-adapts the
        // Malayalam to the revised EN master (the existing editor-form
        // bookkeeping: ML successor re-linked via source_editorial_content_id).
        $revisedEnglish->forceFill([
            'status' => EditorialContent::STATUS_APPROVED,
            'reviewed_by_id' => $editor->id,
        ])->save();
        $revisedMalayalam = $this->adaptMalayalamToMaster($malayalam, $revisedEnglish->id, $editor);

        $application = $workflow->releaseForCustomerPreview($application->fresh(), $editor);

        $revision->refresh();
        $this->assertSame(EditorialRevisionRequest::STATUS_COMPLETED, $revision->status);
        $this->assertSame($editor->id, $revision->processed_by_user_id);
        $this->assertSame(Application::STATUS_EDITORIAL_APPROVED, $application->status);

        /* --------------------------------------------------------------
         * Stage 6 — customer approval of the revised versions.
         * -------------------------------------------------------------- */
        $application = $application->fresh();

        $this->assertSame($revisedEnglish->id, $application->preview_english_editorial_content_id);

        $workflow->approvePreview(
            $application,
            $customer,
            $revisedEnglish->id,
            '127.0.0.1',
            'golden-path-test',
        );

        $application->refresh();
        $this->assertSame(Application::STATUS_AWAITING_PUBLICATION, $application->status);
        $this->assertSame($revisedEnglish->id, $application->customer_approved_english_editorial_content_id);
        $this->assertSame($customer->id, $application->customer_approved_by_user_id);
        $this->assertDatabaseHas('consent_records', ['user_id' => $customer->id]);

        /* --------------------------------------------------------------
         * Stage 7b — post-approval editorial change: the existing rule is
         * that changing the approved master creates a successor version and
         * invalidates the previous customer approval.
         * -------------------------------------------------------------- */
        $successor = app(EditorialContentVersioningService::class)->applyEditorUpdate(
            $revisedEnglish->fresh(),
            ['summary' => self::EN_SUMMARY.' Final reviewed summary confirmed for publication.'],
            $editor,
        );

        $this->assertNotSame($revisedEnglish->id, $successor->id, 'approved narrative is immutable — a successor version is required');
        $this->assertSame($revisedEnglish->version_number + 1, $successor->version_number);
        $this->assertSame(EditorialContent::STATUS_DRAFT, $successor->status);
        $this->assertNull($application->fresh()->customer_approved_english_editorial_content_id, 'previous approval must be invalidated by the change');

        // Editor approves the successor draft, re-adapts the Malayalam to the
        // new master, and re-releases for final sign-off.
        $successor->forceFill([
            'status' => EditorialContent::STATUS_APPROVED,
            'reviewed_by_id' => $editor->id,
        ])->save();
        $finalMalayalam = $this->adaptMalayalamToMaster($revisedMalayalam, $successor->id, $editor);

        $application = $workflow->releaseForCustomerPreview($application->fresh(), $editor);

        /* --------------------------------------------------------------
         * Stage 8 — customer re-approval of the successor version.
         * -------------------------------------------------------------- */
        $workflow->approvePreview(
            $application->fresh(),
            $customer,
            $successor->id,
            '127.0.0.1',
            'golden-path-test',
        );

        $application->refresh();
        $this->assertSame(Application::STATUS_AWAITING_PUBLICATION, $application->status);
        $this->assertSame($successor->id, $application->customer_approved_english_editorial_content_id);
        $this->assertSame($successor->id, $application->customer_approved_english_editorial_content_id, 'final approved version pinned');
        $this->assertSame(2, ConsentRecord::query()->where('user_id', $customer->id)->count(), 'two publication consents (one per approval round)');

        /* --------------------------------------------------------------
         * Stage 9 — final administrative publication (admin-only service).
         * -------------------------------------------------------------- */
        $admin = User::factory()->admin()->create();

        app(ApplicationWorkflowService::class)->publish($application->fresh(), $admin);

        $application->refresh();
        $profile->refresh();
        $successor->refresh();
        $finalMalayalam->refresh();

        $this->assertSame(Application::STATUS_PUBLISHED, $application->status);
        $this->assertSame('published', $profile->status);
        $this->assertNotNull($profile->published_at);
        $this->assertSame($successor->id, $application->published_english_editorial_content_id);
        $this->assertSame($finalMalayalam->id, $application->published_malayalam_editorial_content_id);

        // Audit trail: preview releases + publication (application-subject),
        // customer approvals (approval-record subject).
        $actions = StaffActionLog::query()
            ->where('subject_type', Application::class)
            ->where('subject_id', $application->id)
            ->pluck('action');
        $this->assertTrue($actions->contains(fn ($a) => $a === 'editorial.customer_preview_released'));
        $this->assertTrue($actions->contains(fn ($a) => str_contains((string) $a, 'application.published')));

        $approvalAudit = StaffActionLog::query()
            ->where('subject_type', \App\Models\EditorialCustomerApproval::class)
            ->whereIn('subject_id', \App\Models\EditorialCustomerApproval::query()->where('application_id', $application->id)->pluck('id'))
            ->pluck('action');
        $this->assertTrue($approvalAudit->contains(fn ($a) => $a === 'editorial.customer_approved'), 'customer approval must be audited');

        /* --------------------------------------------------------------
         * Stage 10 — public profile over real HTTP.
         * -------------------------------------------------------------- */
        $slug = $profile->slug;
        $this->assertNotNull($slug);

        $public = $this->get('/'.$slug);
        $public->assertOk();

        $html = $public->getContent();

        // English content. The public page renders the member's name as the
        // heading and does not print the editorial title field; the approved
        // title is therefore asserted on the published binding (below).
        $this->assertSeeAll($html, [$successor->summary, 'chronology confirmed against source material']);
        $this->assertSame(self::EN_TITLE, \App\Models\EditorialContent::query()->findOrFail($application->published_english_editorial_content_id)->title);

        // Malayalam presentation — title asserted on the bound record (the
        // page renders the member name as heading, not the editorial title).
        $ml = $this->get('/'.$slug.'?lang=ml')->getContent();
        $this->assertStringContainsString(self::ML_SUMMARY, $ml);
        $this->assertStringContainsString(self::ML_BODY, $ml);
        $this->assertSame(self::ML_TITLE, \App\Models\EditorialContent::query()->findOrFail($application->published_malayalam_editorial_content_id)->title);

        // Canonical + metadata + JSON-LD.
        $canonical = url('/'.$slug);
        $this->assertStringContainsString('<link rel="canonical" href="'.$canonical.'">', $html);
        $this->assertStringContainsString('name="description" content="'.$successor->summary, $html);
        $this->assertStringContainsString('<title>Golden Path Leader — Jannayaks</title>', $html);

        preg_match_all('/<script type="application\/ld\+json">(.*?)<\/script>/s', $html, $m);
        $this->assertSame(1, count($m[1]));
        $graph = json_decode($m[1][0], true, 512, JSON_THROW_ON_ERROR);
        $types = array_column($graph['@graph'], '@type');
        $this->assertEqualsCanonicalizing(['ProfilePage', 'Person', 'BreadcrumbList'], $types);
        $person = collect($graph['@graph'])->firstWhere('@type', 'Person');
        $this->assertSame('Golden Path Leader', $person['name']);
        $this->assertSame($canonical, $person['url']);

        /* --------------------------------------------------------------
         * Stage 12 — source-material privacy (distinctive-marker probes).
         * -------------------------------------------------------------- */
        $this->assertStringNotContainsString(self::PRIVATE_MARKER, $html);
        $this->assertStringNotContainsString(self::PRIVATE_MARKER, $ml);
        $this->assertStringNotContainsString('Golden Path Leader has served the local community since 2010', $html);
        $this->assertStringNotContainsString('fake-editorial', $html);
        $this->assertStringNotContainsString('AiEditorialRun', $html);
        $this->assertStringNotContainsString('ConsentRecord', $html);
        $this->assertStringNotContainsString('EditorialRevisionRequest', $html);

        /* --------------------------------------------------------------
         * Stage 11 — sitemap eligibility.
         * -------------------------------------------------------------- */
        $sitemap = $this->get('/sitemap.xml');
        $sitemap->assertOk();
        $locs = [];
        $xml = simplexml_load_string($sitemap->getContent());
        foreach ($xml->url as $url) {
            $locs[] = (string) $url->loc;
        }
        $this->assertContains($canonical, $locs, 'published profile must appear in the sitemap at its canonical URL');

        /* --------------------------------------------------------------
         * Stage 13 — integrity/audit trail (consent + run + revision).
         * -------------------------------------------------------------- */
        $this->assertSame(1, AiEditorialRun::query()->where('application_id', $application->id)->where('status', AiEditorialRun::STATUS_SUCCEEDED)->count());
        $this->assertSame(1, EditorialRevisionRequest::query()->where('application_id', $application->id)->count());
        $this->assertSame(2, ConsentRecord::query()->where('user_id', $customer->id)->count());
        $this->assertDatabaseHas('profiles', ['id' => $profile->id, 'slug' => $slug]);
    }

    /**
     * Assert every needle appears in the haystack (readable failure output).
     *
     * @param  list<string>  $needles
     */
    private function assertSeeAll(string $haystack, array $needles): void
    {
        foreach ($needles as $needle) {
            $this->assertStringContainsString($needle, $haystack, 'Expected public page to contain: '.$needle);
        }
    }

    /**
     * Staff Malayalam re-adaptation after an EN master revision: the ML
     * successor version is created through the versioning service and its
     * source master re-linked (the same source_editorial_content_id field the
     * editorial form exposes to staff).
     */
    private function adaptMalayalamToMaster(
        EditorialContent $previousMalayalam,
        int $englishMasterId,
        User $editor,
    ): EditorialContent {
        $successor = app(EditorialContentVersioningService::class)->applyEditorUpdate(
            $previousMalayalam,
            ['summary' => self::ML_SUMMARY, 'body' => self::ML_BODY],
            $editor,
        );

        $successor->forceFill([
            'source_editorial_content_id' => $englishMasterId,
            'status' => EditorialContent::STATUS_APPROVED,
            'reviewed_by_id' => $editor->id,
        ])->save();

        return $successor->fresh() ?? $successor;
    }

    private function doesntHavePublishedProfile(): void
    {
        $this->assertSame(0, Profile::query()->where('status', 'published')->count());
    }
}
