@extends('legal.base', ['legalActive' => 'disclaimer'])

@section('title', 'Disclaimer — Jannayaks')
@section('seoDescription', 'What Jannayaks profiles are and are not: editorial biographies, not endorsements, advice or official records.')
@section('seoCanonical', route('legal.disclaimer'))
@section('legal_heading', 'Disclaimer')
@section('legal_intro', 'Please keep the following in mind when you read anything on Jannayaks.')

@section('legal_body')
<h2>Editorial profiles, not endorsements</h2>
<p>Jannayaks publishes biographical profiles and memorial pages prepared with the people they describe, or with their families. A profile is not an endorsement, recommendation or ranking by Jannayaks or Aurex Network. The three tiers describe the kind of profile a person has chosen, not our opinion of their worth. We are politically neutral and are not connected with any political party or government.</p>

<h2>How write-ups are prepared</h2>
<p>Write-ups are prepared by our editorial team, with the help of artificial intelligence, from information supplied by the person or their family. Our human editors review each one, and the person approves it before it is published. We take care over accuracy, but we cannot independently verify every statement. The facts and views in a profile are those supplied by the subject or their family.</p>

<h2>Identity verification</h2>
<p>We check the identity of each living person we profile. This confirms who they are. It does not confirm their claims, achievements, public office or good character.</p>

<h2>Not official records or advice</h2>
<p>Profiles are not official government records, legal documents, or professional advice of any kind. Please do not rely on a profile for legal, financial, electoral or other important decisions. Check with the relevant authority.</p>

<h2>Demonstration profiles</h2>
<p>The profiles in our Demo section are fictional. They do not describe real people, and their portraits are generated by artificial intelligence.</p>

<h2>Translation</h2>
<p>Our Malayalam and English write-ups are prepared by our editors. Other languages are produced automatically by the Google translation widget and may contain errors. If the versions differ, the Malayalam and English versions prepared by us are the reference.</p>

<h2>Links and third parties</h2>
<p>A profile may link to external websites or videos supplied by the subject. We do not control them and are not responsible for their content.</p>

<h2>Corrections</h2>
<p>If you find something inaccurate, please tell us through our <a href="{{ route('legal.grievance') }}">Grievance Redressal</a> process and we will review it promptly. Our <a href="{{ route('legal.terms') }}">Terms &amp; Conditions</a> and <a href="{{ route('legal.privacy') }}">Privacy Policy</a> also apply.</p>
@endsection
